# Generated by Django 3.2.12 on 2022-02-15 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streetanimal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_no', models.AutoField(primary_key=True, serialize=False)),
                ('adopter_name', models.CharField(db_index=True, max_length=30)),
                ('monthly_income', models.IntegerField()),
                ('residential_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Housing', 'Housing'), ('Oneroom', 'Oneroom'), ('Officetel', 'Officetel')], default='Apartment', max_length=10)),
                ('have_pet_or_not', models.BooleanField()),
                ('picture_of_residence1', models.ImageField(upload_to='')),
                ('picture_of_residence2', models.ImageField(upload_to='')),
                ('picture_of_residence3', models.ImageField(upload_to='')),
                ('place_to_meet', models.CharField(choices=[('Seoul', '서울 강동구청 반려동물팀'), ('Daejeon', '대전 동물 보호 센터'), ('Saejong', '세종 유기동물 보호센터'), ('Daegu', '대구 유기동물 보호 협회'), ('Busan', '부산 동물보호센터')], default='Seoul', max_length=20)),
                ('date_to_meet', models.DateField()),
                ('status', models.CharField(choices=[('1', '신청'), ('2', '심사 중'), ('3', '수락'), ('4', '교육 중'), ('5', '입양 완료'), ('6', '거절')], db_index=True, default=1, max_length=3)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streetanimal.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
