# Generated by Django 3.2.12 on 2022-02-07 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streetanimal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_no', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_income', models.IntegerField()),
                ('residential_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Housing', 'Housing'), ('Oneroom', 'Oneroom'), ('Officetel', 'Officetel')], max_length=10)),
                ('have_pet_or_not', models.BooleanField()),
                ('picture_of_residence1', models.ImageField(upload_to='')),
                ('picture_of_residence2', models.ImageField(upload_to='')),
                ('picture_of_residence3', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=30)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetanimal.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
