# Generated by Django 3.2.12 on 2022-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptassignment',
            name='place_to_meet',
            field=models.CharField(choices=[('Seoul', '서울 강동구청 반려동물팀'), ('Daejeon', '대전 동물 보호 센터'), ('Saejong', '세종 유기동물 보호센터'), ('Daegu', '대구 유기동물 보호 협회'), ('Busan', '부산 동물보호센터')], default='Seoul', max_length=20),
        ),
    ]
