# Generated by Django 3.2.12 on 2022-02-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetanimal', '0001_initial'),
        ('adopt_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptassignment',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streetanimal.animal'),
        ),
    ]
