# Generated by Django 3.2.12 on 2022-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptassignment',
            name='residential_type',
            field=models.CharField(choices=[('아파트', '아파트'), ('빌라', '빌라'), ('주택', '주택'), ('원룸', '원룸'), ('오피스텔', '오피스텔')], default='아파트', max_length=50),
        ),
    ]
