# Generated by Django 3.2.12 on 2022-03-03 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_assignment', '0002_alter_adoptassignment_place_to_meet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptassignment',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='adoptassignment',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
