# Generated by Django 3.2.12 on 2022-02-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_assignment', '0003_alter_adoptassignment_place_to_meet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptassignment',
            name='status',
            field=models.CharField(choices=[('신청', '신청'), ('심사 중', '심사 중'), ('수락', '수락'), ('교육 중', '교육 중'), ('입양 완료', '입양 완료'), ('거절', '거절')], db_index=True, default='신청', max_length=50),
        ),
    ]
