# Generated by Django 3.2.12 on 2022-02-24 13:46

import adopt_assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_assignment', '0004_alter_adoptassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptassignment',
            name='picture_of_residence1',
            field=models.ImageField(upload_to='', validators=[adopt_assignment.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='adoptassignment',
            name='picture_of_residence2',
            field=models.ImageField(upload_to='', validators=[adopt_assignment.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='adoptassignment',
            name='picture_of_residence3',
            field=models.ImageField(upload_to='', validators=[adopt_assignment.models.validate_image]),
        ),
    ]
