# Generated by Django 3.2.12 on 2022-02-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_assignment', '0005_auto_20220224_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptassignment',
            options={'ordering': ['-assignment_no']},
        ),
        migrations.AlterField(
            model_name='adoptassignment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adoptassignment',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
