# Generated by Django 3.2.12 on 2022-02-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopt_assignment', '0001_initial'),
        ('adopt_review', '0001_initial'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_no', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(blank=True, max_length=30)),
                ('assignment_no', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adopt_assignment.adoptassignment')),
                ('notice_no', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='notice.notice')),
                ('review_no', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adopt_review.review')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
