# Generated by Django 3.2.12 on 2022-02-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='adopt_assignment',
            new_name='adoptassignment',
        ),
    ]
