# Generated by Django 3.2.12 on 2022-02-24 13:46

import adopt_review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', validators=[adopt_review.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', validators=[adopt_review.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', validators=[adopt_review.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='review',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', validators=[adopt_review.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='review',
            name='image5',
            field=models.ImageField(blank=True, upload_to='', validators=[adopt_review.models.validate_image]),
        ),
    ]
