# Generated by Django 3.2.12 on 2022-02-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_quiz',
            field=models.CharField(choices=[('1', '내 보물1호는?'), ('2', '처음 키운 반려동물 이름은?'), ('3', '어머니 성함은?'), ('4', '아버지 성함은?'), ('5', '좋아하는 음식은?')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('1', 'Seoul'), ('2', 'Busan'), ('3', 'Daegu'), ('4', 'Incheon'), ('5', 'Daejeon'), ('6', 'Sejong'), ('7', 'Gwangju'), ('8', 'Ulsan'), ('9', 'Jeju'), ('10', 'Gangwon')], max_length=7),
        ),
    ]
