# Generated by Django 3.2.12 on 2022-02-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetanimal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='protection_status',
            field=models.CharField(choices=[('입양 대기', '입양 대기'), ('입양 매칭 중', '입양 매칭 중'), ('입양 완료!', '입양 완료!')], default='입양 대기', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('암컷', '암컷'), ('수컷', '수컷')], default='암컷', max_length=30),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('소형', '소형'), ('중형', '중형'), ('대형', '대형')], default='소형', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('강아지', '강아지'), ('고양이', '고양이')], db_index=True, max_length=30, primary_key=True, serialize=False, verbose_name='품종'),
        ),
    ]
