# Generated by Django 3.2.12 on 2022-03-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetanimal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-animal_no']},
        ),
    ]
