# Generated by Django 3.2.12 on 2022-02-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetanimal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='place_of_discovery',
            field=models.CharField(max_length=30),
        ),
    ]
