# Generated by Django 3.2.12 on 2022-02-24 13:46

from django.db import migrations, models
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', validators=[notice.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', validators=[notice.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', validators=[notice.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', validators=[notice.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image5',
            field=models.ImageField(blank=True, upload_to='', validators=[notice.models.validate_image]),
        ),
    ]
