# Generated by Django 3.2.12 on 2022-02-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attached_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfile',
            name='att_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
